---
- name: Install and configure Vault Agent
  hosts: localhost
  become: true

  vars:
    vault_version: "1.7.2"  # Update with the desired Vault version
    vault_agent_config_path: "/etc/vault.d/vault-agent.hcl"

  tasks:
    - name: Install Vault
      apt:
        name: "vault-{{ vault_version }}"
        state: present

    - name: Create Vault Agent configuration directory
      file:
        path: "{{ vault_agent_config_path | dirname }}"
        state: directory

    - name: Generate Vault Agent configuration
      template:
        src: vault-agent.hcl.j2
        dest: "{{ vault_agent_config_path }}"
      notify: Restart Vault Agent

    - name: Start Vault Agent service
      systemd:
        name: vault-agent
        state: started
        enabled: true

  handlers:
    - name: Restart Vault Agent
      systemd:
        name: vault-agent
        state: restarted
